# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025ce1097d1d1c2a3d046cfbdc232f06d9d703c74a7d5479de26b7e291f4b1b7520967d84778324823034510f1914353a39d97f5becff4ff00a30137fe582c17

test:
  secret_key_base: 4f820b153852201ac736144b1a656c595b16e10b3502d9a71ee0922273947e2b6ca8c2eddce4e0d0f4c643e4ee5f60ed47dd0dc6859f07e76a61a0286af74a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
